### ISSUE TITLE
Can't go "full leet"?

### ISSUE THREAD

**Issue by 7MinSec** [digininja/RSMangler#7]
Hello!

I'm looking to go "full leet" on a word list file of mine with:

````
./rsmangler.rb --file myfile.txt -T
````

When I do I get:

````
./rsmangler.rb:392:in `gsub!': can't convert Array into String (TypeError)
        from ./rsmangler.rb:392:in `block (2 levels) in <main>'
        from ./rsmangler.rb:391:in `each_pair'
        from ./rsmangler.rb:391:in `block in <main>'
        from ./rsmangler.rb:360:in `each'
        from ./rsmangler.rb:360:in `<main>'
````

The other options like `-e` and `-t` seem to work fine.

Thanks,
Brian

**Comment by dmcxblue** [comment]
Same issues here looks like its just the -T option

**Comment by 7MinSec** [comment]
Just thought I'd give this a bump as I'm trying rsmangler for another assessment and "full leet" gives:

````
Traceback (most recent call last):
	5: from /opt/rsmangler/rsmangler.rb:362:in `<main>'
	4: from /opt/rsmangler/rsmangler.rb:362:in `each'
	3: from /opt/rsmangler/rsmangler.rb:393:in `block in <main>'
	2: from /opt/rsmangler/rsmangler.rb:393:in `each_pair'
	1: from /opt/rsmangler/rsmangler.rb:394:in `block (2 levels) in <main>'
/opt/rsmangler/rsmangler.rb:394:in `gsub!': no implicit conversion of Array into String (TypeError)
````

**Comment by sieira** [comment]
+1

**Comment by behindblackwalls** [comment]
+ 1
